load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


http_archive(
    name = "Openssl",
    strip_prefix = "openssl-OpenSSL_1_1_0h",
    url = "https://github.com/openssl/openssl/archive/OpenSSL_1_1_0h.tar.gz",
        build_file_content =
"""
# TODO(keir): Replace this with a better version, like from TensorFlow.
# See https://github.com/ceres-solver/ceres-solver/issues/337.
cc_library(
    name = 'openssl',
    srcs = [],
    includes = ['.'],
    hdrs = glob(['openssl/**']),
    visibility = ['//visibility:public'],
)
"""
)


