load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


http_archive(
    name ="a",
    strip_prefix = "jsoncpp-1.9.2",
   # build_file = "//:jsoncpp.BUILD",
    urls = ["https://github.com/open-source-parsers/jsoncpp/archive/1.9.2.tar.gz",],
        build_file_content =
"""
# TODO(keir): Replace this with a better version, like from TensorFlow.
# See https://github.com/ceres-solver/ceres-solver/issues/337.
cc_library(
    name = 'josncpp',
    srcs = [],
    includes = ['.'],
    hdrs = glob(['jsoncpp/**']),
    visibility = ['//visibility:public'],
)
"""
)
